### ISSUE TITLE
tillträdande inspektorn tycker...

### ISSUE THREAD

**Issue by bjornregnell** [Dsek-LTH/sjungbok#3]
...att det på denna planet sjungs för lite sånger som hyllar planetens coolaste språk.

Och därför undrar jag hur jag gör för att övertala repots makthavare att inkludera snart spojlade, ännu hemliga, inspektorsgyckel i sjungboken?

**Comment by finurligt** [comment]
Jag tycker det låter högst rimligt att den tillträdande inspektorn ska kunna ha ett inspektorsgyckle i sjungboken! Framförallt om det håller en hög kvalité ;)

Antingen kan du göra det själv genom att lägga en merge request där du lagt till låten i lämpligt kapitel på lämplig plats, eller så kan du maila text och melodi till mig så kan jag lösa det :)

Min mail är mat14fsu@student.lu.se

**Comment by bjornregnell** [comment]
Tack för info. Jag provar skapa infogningsbegäran. Egentligen är det två låtar... men jag kanske måste hejda mig och välja en? Eller borde någon annan välja vilken som är bäst, om inte båda kan gå för sig?

**Comment by bjornregnell** [comment]
Jag kom precis även på denna och vill dryfta med sjungboksdignitärer om den har erfoderlig kvalitet. Jag tänker att det är fint att 1) det finns flöer visor utan dryckestema och 2) att våra internationella sektionsmedlemmar har ngt att bita i.

```
Titel: Kryptofil
Melodi: Far jag kan inte få upp min kokosnöt (Povel Ramel, 1950)

Far jag kan inte få upp min kryptofil
Inte ens med sudo eller root
Jag provade med rm minus rf och en slash
Å nu finns ej kvar mina kryptocash

DÄRHEMMA!

Daddy I can't crack my crypto file
Neither using sudo nor with root
I tried with rm blank dash rf blank and then a slash
And now it's gone my precious crypto-cash

```
Om tillfälle ges så sjunger jag den frammåt sent på skiphtesqasquenatten för att demonstrera hur det är tänkt med osnubbliga stavelser etc.

**Comment by bjornregnell** [comment]
Och här är min hyllningssång till specifikt programmeringsspråk: (Spoiler alert för inspektorsgyckel å skiphtesgasque 2023)
```
Titel: Bella Scala
Melodi: Bella Notte, Lady och Lufsen \url{https://youtu.be/TE9E1FEMnGY}
(Inspektorsgyckel Skiphtesgasque 2023)

Å detta språk detta ljuvliga språk
som vi kallar bella Scala

Se vilken syn alla uttryck i skyn
detta ljuva bella Scala

Fjärran från det du älskar blir koden ödsligt tom
men i dess närhet sluts du in i dess trolska rikedom

Åh åh detta språk -- det är ungdomens språk
som vi kallar bella Scala*

```
* eftersom vi lever i en demokrati får alla ha vilket favpritspråk de vill och därför är det brukligt att alla gasquedeltagare på SISTA ordet på SISTA raden sjunger ut namnet på sitt eget favoritsrpåk med EMFAS.

**Comment by bjornregnell** [comment]
Men allra först en PR med lämplig gitignore innan jag råkar pusha diverse slaskfiler... https://github.com/Dsek-LTH/sjungbok/pull/4
